services:
  postgresDB:
    image: postgres:15.1
    container_name: taskrr
    restart: always
    environment:
      - POSTGRES_DB=taskrr_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"